### ISSUE TITLE
Objective-C new app users cannot have lowercase usernames

### ISSUE THREAD

**Issue by RogerTangos** [abhardwaj/datahub#13]
If the username provided is lowercase, the thrift files throw an unknown exception

**Comment by abhardwaj** [comment]
ah.. you are saying case-sensitive stuff -- ok, will fix it.

**Comment by RogerTangos** [comment]
Are you updating at right this moment? I'm randomly getting some connection
errors

Albert Carter

Programmer
Big Data Initiative
CSAIL, MIT

**Comment by RogerTangos** [comment]
Not sure if fixed or not, but I'm marking it as wontfix and closed, since the account creation api is deprecated.
